apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  labels:
    release: prometheus # optional-depends if we used serviceMonitorNamespaceSelector or serviceMonitorSelectorNilUsesHelmValues
    app: prometheus     # optional
spec:
  jobLabel: job # optional
  endpoints:
    - interval: 5s
      port: flask-web
      path: /metrics
  selector:
    matchLabels:
      app: service-api
