apiVersion: v1
kind: Service
metadata:
  name: front-api
spec:
  selector:
    app: front-api
  ports:
    - protocol: TCP
      port: 5000 # port exposed internally in the cluster
      targetPort: 5000 # the container port to send requests to
