apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ index .Values.ingress.hosts 0 "host" }}
    http:
      paths:
        - path: {{ index .Values.ingress.hosts 0 "paths" 0 "path" }}
          pathType: Prefix
          backend:
            service:
              name: front-api
              port:
                number: {{ .Values.ContainerPortNumber }}

