apiVersion: v1
kind: Service
metadata:
  name: back-api
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: back-api
